export default {
    '/': '工作台',
    '/home/': '工作台',
    "/home/purCatalog/": "采购目录",
    "/home/outStock/": "缺样上报",
    "/home/outStock/reportdetail/": '详情',
    '/menubar/': '菜单中心',
    '/menubar/unified-menu/': '统一菜单',
    '/menubar/unified-menu/details/': '详情',
    '/menubar/unified-menu/adjust/': '调整菜单',
    '/menubar/my-menu/': '我的菜单',
    '/menubar/my-menu/details/': '详情',
    '/menubar/my-menu/custom/': '自建菜单',
    '/menubar/my-menu/adjust/': '调整菜单',
    '/menubar/my-menu/choice-template/': '选择模板',
    '/menubar/my-menu/from-template/': '从模板新建',
    '/menubar/menu-template/': '菜单模板',
    '/menubar/menu-template/details/': '模板详情',
    '/menubar/menu-template/update/': '编辑模板',
    '/menubar/menu-template/new/': '新建模板',
    '/menubar/public/details/': '详情',
    '/menubar/private/': '我的菜单',
    '/menubar/private/new/': '新增',
    '/menubar/private/details/': '详情',
    '/menubar/template/': '详情',
    '/menubar/template/new/': '详情',
    '/accSupermarket/': '辅料超市',
    '/purOrder/': '采购订单',
    '/purOrder/new/': '新建订单',
    '/purOrder/details/': '详情',
    '/delivery/': '配送验收',
    '/parameter/': '台帐',
    '/parameter/purcatalog/': '采购目录',
    '/parameter/details/': '详情',
    '/setting/information/': '设置',
    '/setting/set/': '设置',
    '/setting/security/': '设置',
    '/setting/cuisine/': '设置',
    '/setting/': '设置',
    '/Setting/outStock/':'缺样上报',
    '/Setting/outStock/reportdetail/':'详情',
    '/ingredetail/':'食材详情',
    '/excipientdetail/':'辅料详情',
    '/purCatalog/': '采购目录',
    '/purCatalog/ingredetail/': '详情'
}